### ISSUE TITLE
Error in Ubuntu 16.04.2 LTS 

### ISSUE THREAD

**Issue by bigslipper** [NCAR/lrose-core#10]
Hi i downloaded the radx-20170315.x86_64 version bin distro;
after installation this the prompt 
/usr/local/radxprint/bin/RadxPrint: symbol lookup error: /usr/local/radxprint/lib/libRadx.so.0: undefined symbol: _ZN2H56H5File6isHdf5ERKSs

Some suggest?
Thanks Alex

**Comment by mjskier** [comment]
This symbol comes from the libhdf5_cpp.so library.
The binary release comes with all the libraries (including libhdf5_cpp.so)
packaged in a lib directory. But you need to point LD_LIBRARY_PATH to that
lib directory.
Can you try this?

LD_LIBRARY_PATH=/path/to/your/lrose/installation/lib RadxPrint

This works for me on a Mint system (derived from Ubuntu 14.x) I don't have
a 16.x system to try.

Bruno.

**Comment by bigslipper** [comment]
Thanks Bruno,
I made i file conf in /etc/ld.so.conf.d  with path to  radxprint's installation lib directory
Now run. :^))
Alex
