### ISSUE TITLE
Radx2Grid: data not being censored

### ISSUE THREAD

**Issue by leavesntwigs** [NCAR/lrose-core#100]
When I try to censor data, I'm still seeing bad data get through. In the examples in the folder, I'm attempting to censor all variables based on RHO and DBZ (as a test), but if you look at the final .nc file, there are still many data points with RHO values < 0.8, despite my parameter settings (lines 1278, 1327-1340).

**Comment by mike-dixon** [comment]
Fixed in 20221229 release.
