### ISSUE TITLE
CIDD segmentation fault running topaz binary on Ubuntu 20.04 LTS

### ISSUE THREAD

**Issue by leavesntwigs** [NCAR/lrose-core#108]
Running Ubuntu 20.04 LTS and the most recent LROSE source.  The LROSE-CORE all compiled fine and runs.  CIDD is a different story.   Loaded the 32-bit support packages, the fonts, installed the binary version and attempted to run it using the instructions given in the documentation.  Seg fault.  Same story when running it with existing project configurations (before and after updating the params file.  I tried to compile the source using cmake and auto scripts but they both failed for different reasons.

**Comment by mike-dixon** [comment]
This problem is resolved by installed CIDD from the CIDD binary release:
  lrose-cidd-20210524.bin.x86_64.tgz
This is available via the latest release.
