### ISSUE TITLE
Files named 'aux' prevent checkout on Windows

### ISSUE THREAD

**Issue by jbuonagurio** [NCAR/lrose-core#12]
The name 'aux' can't be used as a file or folder name in Windows, for historical reasons (it was an MS-DOS device name). It's not possible to do a regular Git checkout on Windows due to the following files:

/codebase/libs/xview/src/imcb/aux.c
/codebase/libs/xview/src/include/xview_private/aux.h

One workaround is to do a sparse checkout.

**Comment by leavesntwigs** [comment]
Thank you for determining the problem with 'aux' names.  We are evaluating the issue and will be in contact soon.

**Comment by mike-dixon** [comment]
This has been fixed.
In the libs/xview library, we renamed aux.h -> aux_data.h, and aux.c -> aux_data.c
