### ISSUE TITLE
Iso c++ forbids comparison between pointer and integer -fpermissive 

### ISSUE THREAD

**Issue by rpelorosso** [NCAR/lrose-core#14]
Hi!

I was getting the error mentioned in the title while compiling. I fixed the error and wanted to create a pull request, but I don't have permissions, it seems, to create a new branch. So I'm attaching here a patch for fixing it.  (sorry about the .zip file, github wouldn't allow me to upload a .patch file directly)

Regards!

[fix-pointer-integer-comparison.zip](https://github.com/NCAR/lrose-core/files/1273650/fix-pointer-integer-comparison.zip)

**Comment by leavesntwigs** [comment]
Terrific!  Thank you so much for finding and fixing the error.
Brenda

**Comment by burghart** [comment]
Fixed by 65c3ed68c2c0e517157cb1435b288c31738a4621
