### ISSUE TITLE
Where can I find the CIDD executable?

### ISSUE THREAD

**Issue by rpelorosso** [NCAR/lrose-core#16]
Hi! I know there's a built package in [cidd-20170314.x86_64.tgz](https://github.com/NCAR/lrose-core/releases/download/cidd-20170314/cidd-20170314.x86_64.tgz) but I don't see the CIDD executable there. I remember downloading it in the past. Has it been removed?

Thanks!

**Comment by mike-dixon** [comment]
I apologize about that.
The latest CIDD release has the full set of apps - including CIDD.
Mike
