### ISSUE TITLE
Cannot install LROSE on linux

### ISSUE THREAD

**Issue by hhuangwx** [NCAR/lrose-core#19]
I've tried to compile lrose following the guidance in https://github.com/NCAR/lrose-core/blob/master/docs/README_BUILD.md for several times on both osx and linux(ubuntu). 
None of the methods (NCAR build system, or automake) works for me. Something is wrong in the following step.

```
cd $codebaseDir/libs/tdrp/src
make -j 8 opt
make install
```

There is no rules for generate the makefile inside this directory. Please tell me how can I fix this.
Thank you.

**Comment by mike-dixon** [comment]
Hi
Could you try again with the latest release?
If the build fails, please provide the exact details of what commands you are running, and what the error messages are.
Thanks
Mike

**Comment by hhuangwx** [comment]
OK, I'll paste my error messages later on.

**Comment by hhuangwx** [comment]
First, I started the installation from the cloned rep. from github, following the instruction [README_NCAR_BUILD.md](https://github.com/NCAR/lrose-core/blob/master/docs/README_NCAR_BUILD.md).
The environmental variable LROSE_INSTALL_DIR and LROSE_CORE_DIR had already been set, and the required netcdf/hdf5 packages have been installed.

![s2](https://user-images.githubusercontent.com/11309009/31594537-180e7cb2-b1fb-11e7-8980-9b3129ecbe78.png)
![s3](https://user-images.githubusercontent.com/11309009/31594541-1fb41ad0-b1fb-11e7-8881-df9af3558be0.png)

I found the install_package_makefiles.py script didn't copy the makefile to the directory $LROSE_CORE_DIR/codebase/libs/tdrp/src, which finally caused the problem.

**Comment by mike-dixon** [comment]
I see you are using Dropbox - are you sure you are not running out of space?

**Comment by hhuangwx** [comment]
I'm sure I have enough space for my Dropbox. I'm not sure whether the developers compile LROSE using the exact procedures shown in the README file.

**Comment by mike-dixon** [comment]
There are now pre-built packages for most common LINUX dirstibutions.
For example see:
https://github.com/NCAR/lrose-core/releases/tag/lrose-core-20191213
