### ISSUE TITLE
RadxConvert: corrupted rays when converting from SIGMET

### ISSUE THREAD

**Issue by juhi24** [NCAR/lrose-core#26]
I have a weird problem with SIGMET (IRIS) raw --> cfradial conversion using `RadxConvert`. I have scans from 3 C-band radars every 5 minutes that I'm converting. For one of the radars, for the two lowest elevations of every third volume scan (??) I get very weirds patterns in the converted files that don't exist in the original raw data. For every other radar and elevation angle, the there are no such problems.

This is visualized below for DBZ, but similar patterns exists in all fields in the converted cfrad file. In the corrupted rays, the values are not constant but e.g. for DBZ range roughly from -320 to -200 (blue rays in Fig. 2) and -4 to -1 (green).

I had this problem already with an older version of radx. After upgrading to the newest lrose release, the problem still persists. Any ideas how to debug or get around this? Do you suspect there's something wrong with my config (attached below) or is this a bug?

Fig. 1: SIGMET raw DBZ plot using pyart (everything seems to be OK):
![van_raw](https://user-images.githubusercontent.com/399854/33071923-223d17b0-cec6-11e7-8619-0e45235f37fb.png)

Fig. 2: Here's what the same field looks like after converting to cfradial (some rays go crazy):
![van_cfrad](https://user-images.githubusercontent.com/399854/33071910-146ae1d0-cec6-11e7-90d5-6063ad162f0f.png)

Here are the conversion parameters used: [convert_params.txt](https://github.com/NCAR/lrose-core/files/1491268/convert_params.txt)

EDIT1: Here is an example of a problematic raw file (same as used in the Fig. 2): 
[201708120010_VAN.PPI3_A.raw.zip](https://github.com/NCAR/lrose-core/files/1495911/201708120010_VAN.PPI3_A.raw.zip)
EDIT2: Here is a corresponding raw file from a non-problematic task:
[201708120005_VAN.PPI2_A.raw.zip](https://github.com/NCAR/lrose-core/files/1501204/201708120005_VAN.PPI2_A.raw.zip)

**Comment by mike-dixon** [comment]
The bug was in SigmetRadxFile::_readSweepData(). The number of fields had an arbitrary maximum of 16, so when data with more than 16 fields was encountered the but showed up. This has been fixed to allow for an arbitrary number of fields.
