### ISSUE TITLE
RadxConvert SIGMET conversion omits/modifies instrument parameters

### ISSUE THREAD

**Issue by stechma2** [NCAR/lrose-core#3]
This is specifically related to the 20160809 version of Radx, though very likely still applies in the more recent builds (untested with current LROSE release due to separate issue).

I am using data from the NOAA P-3 Tail Doppler Radar (TDR) collected during the PECAN field campaign. The raw data files are in the SIGMET Raw format (the TDR was using RVP-8 at the time). In trying to implement a dual-PRF outlier correction, it has become apparent that a number of PRT/PRF instrument parameters are changed/omitted when these files are converted to cfradial or dorade formats (likely other formats as well, though untested). The most notable examples I have found include:
* `prf_flag` variable **omitted**
* `prt_mode` **changed** from `"dual"` to `"fixed"`
* `prt_ratio` **truncated** from `1.33333...` (4/3) to `1.0`

The original SIGMET file and resultant cfradial file can be downloaded from Google Drive here (I was unable to attach them to this issue):
[https://drive.google.com/drive/folders/0B3S2dfg0gI7zNUtvV3EwcVVDRE0?usp=sharing](https://drive.google.com/drive/folders/0B3S2dfg0gI7zNUtvV3EwcVVDRE0?usp=sharing)
Additionally, I have included an iPython notebook illustrating the differences in these parameters between the two files (leveraging the Py-ART package for reading the raw/cfradial files).

The extra verbose output from RadxConvert is available here:
[RadxConvert_sigmet-cfrad_verboseOutput.txt](https://github.com/NCAR/lrose-core/files/921107/RadxConvert_sigmet-cfrad_verboseOutput.txt)

Please let me know if you need additional information.

**Comment by stechma2** [comment]
Didn't realize I could attach zipped files. Here is everything I referred to in the original post (in case this is easier than dealing with Google Drive):
[RadxTests.zip](https://github.com/NCAR/lrose-core/files/922321/RadxTests.zip)

**Comment by mike-dixon** [comment]
Date 2017/12/06.
Commit eb718a8a646937961f4f3982a50395bc97df0e1a.
Added _prtRatio and _prtDual to SigmetRadxFile class, to fix the bugs related to dual prt mode.
This appears to work correctly now.
