### ISSUE TITLE
build_auto issue

### ISSUE THREAD

**Issue by joshua-wx** [NCAR/lrose-core#30]
Hi Mike,

I've caught a snag running the auto build script for lrose. lrose-netcdf installed with no problems and the python makefile generator worked fine. I'm running fedora 27 64-bit.

Here's the error below, please let me know what you think.

Cheers,
Joshua

`running cmd: /home/meso/dev/lrose-core/codebase/make_bin/createMakefile.am.app.radx.py --dir ./apps/spdb_utils/src/run_PrintSigAirMet --libList Mdv,dataport,didss,dsdata,dsserver,euclid,Fmq,physics,rapformats,rapmath,rapplot,tdrp,toolsa
ERROR -  createMakefile.am.app.radx.py
  Cannot find TARGET_FILE in  __makefile.template
  dir:  ./apps/spdb_utils/src/run_PrintSigAirMet
Traceback (most recent call last):
  File "./make_bin/createConfigure.am.py", line 475, in <module>
    main()
  File "./make_bin/createConfigure.am.py", line 98, in main
    searchDir(appsDir)
  File "./make_bin/createConfigure.am.py", line 259, in searchDir
    searchDir(subdirPath)
  File "./make_bin/createConfigure.am.py", line 259, in searchDir
    searchDir(subdirPath)
  File "./make_bin/createConfigure.am.py", line 259, in searchDir
    searchDir(subdirPath)
  File "./make_bin/createConfigure.am.py", line 246, in searchDir
    runCommand(cmd)
  File "./make_bin/createConfigure.am.py", line 460, in runCommand
    retcode = subprocess.check_call(cmd, shell=True)
  File "/usr/lib64/python2.7/subprocess.py", line 186, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '/home/meso/dev/lrose-core/codebase/make_bin/createMakefile.am.app.radx.py --dir ./apps/spdb_utils/src/run_PrintSigAirMet --libList Mdv,dataport,didss,dsdata,dsserver,euclid,Fmq,physics,rapformats,rapmath,rapplot,tdrp,toolsa' returned non-zero exit status 1`

**Comment by joshuass** [comment]
Full output from build script
`[meso@localhost lrose-core]$ ./build/build_auto -p radx -x /home/meso/lrose
Running build_auto
  package: radx
  prefix: /home/meso/lrose
  runDir: /home/meso/dev/lrose-core
Removing ./libs/makefile
Removing ./apps/scripts/src/makefile
Removing ./apps/procmap/src/makefile
Removing ./apps/Radx/src/makefile
Removing ./apps/radar/src/makefile
Removing ./apps/tdrp/src/makefile
Removing ./apps/makefile
Copying ./libs/_makefiles/makefile.radx to ./libs/makefile
Copying ./apps/scripts/src/_makefiles/makefile.radx to ./apps/scripts/src/makefile
Copying ./apps/procmap/src/_makefiles/makefile.radx to ./apps/procmap/src/makefile
Copying ./apps/Radx/src/_makefiles/makefile.radx to ./apps/Radx/src/makefile
Copying ./apps/radar/src/_makefiles/makefile.radx to ./apps/radar/src/makefile
Copying ./apps/tdrp/src/_makefiles/makefile.radx to ./apps/tdrp/src/makefile
Copying ./apps/_makefiles/makefile.radx to ./apps/makefile
Running run_autoconf
  package: radx
  debug: true
  verbose: false
  static: false

*********************************************************************

  Running autoconf for radx release

  NCAR, Boulder, CO, USA

  2018/02/11 10:31:29

*********************************************************************

Removing ./libs/makefile
Removing ./apps/scripts/src/makefile
Removing ./apps/procmap/src/makefile
Removing ./apps/Radx/src/makefile
Removing ./apps/radar/src/makefile
Removing ./apps/tdrp/src/makefile
Removing ./apps/makefile
Copying ./libs/_makefiles/makefile.radx to ./libs/makefile
Copying ./apps/scripts/src/_makefiles/makefile.radx to ./apps/scripts/src/makefile
Copying ./apps/procmap/src/_makefiles/makefile.radx to ./apps/procmap/src/makefile
Copying ./apps/Radx/src/_makefiles/makefile.radx to ./apps/Radx/src/makefile
Copying ./apps/radar/src/_makefiles/makefile.radx to ./apps/radar/src/makefile
Copying ./apps/tdrp/src/_makefiles/makefile.radx to ./apps/tdrp/src/makefile
Copying ./apps/_makefiles/makefile.radx to ./apps/makefile
Running createConfigure.am.py:
  Top level dir:  .
  Base file name:  configure.base.shared
  shared:  True
  pkg:  radx
running cmd: /home/meso/dev/lrose-core/codebase/make_bin/createMakefile.am.topdir.py --dir . --debug
Running createMakefile.am.topdir.py:
  Dir:  .
  libs dir:  libs
  apps dir:  apps
  Getting lib list from dir:  libs
  Searching makefile template:  libs/__makefile.template
  libList:  Mdv,dataport,didss,dsdata,dsserver,euclid,Fmq,physics,rapformats,rapmath,rapplot,tdrp,toolsa
  Searching dir:  libs
running cmd: /home/meso/dev/lrose-core/codebase/make_bin/createMakefile.am.recurse.py --dir ./libs
  Searching dir:  libs/Mdv
running cmd: /home/meso/dev/lrose-core/codebase/make_bin/createMakefile.am.recurse.py --dir ./libs/Mdv
  Searching dir:  libs/Mdv/src
running cmd: /home/meso/dev/lrose-core/codebase/make_bin/createMakefile.am.lib.py --dir ./libs/Mdv --shared  --libList Mdv,dataport,didss,dsdata,dsserver,euclid,Fmq,physics,rapformats,rapmath,rapplot,tdrp,toolsa
  Searching dir:  libs/dataport
running cmd: /home/meso/dev/lrose-core/codebase/make_bin/createMakefile.am.recurse.py --dir ./libs/dataport
  Searching dir:  libs/dataport/src
running cmd: /home/meso/dev/lrose-core/codebase/make_bin/createMakefile.am.lib.py --dir ./libs/dataport --shared  --libList Mdv,dataport,didss,dsdata,dsserver,euclid,Fmq,physics,rapformats,rapmath,rapplot,tdrp,toolsa
  Searching dir:  libs/didss
running cmd: /home/meso/dev/lrose-core/codebase/make_bin/createMakefile.am.recurse.py --dir ./libs/didss
  Searching dir:  libs/didss/src
running cmd: /home/meso/dev/lrose-core/codebase/make_bin/createMakefile.am.lib.py --dir ./libs/didss --shared  --libList Mdv,dataport,didss,dsdata,dsserver,euclid,Fmq,physics,rapformats,rapmath,rapplot,tdrp,toolsa
  Searching dir:  libs/dsdata
running cmd: /home/meso/dev/lrose-core/codebase/make_bin/createMakefile.am.recurse.py --dir ./libs/dsdata
  Searching dir:  libs/dsdata/src
running cmd: /home/meso/dev/lrose-core/codebase/make_bin/createMakefile.am.lib.py --dir ./libs/dsdata --shared  --libList Mdv,dataport,didss,dsdata,dsserver,euclid,Fmq,physics,rapformats,rapmath,rapplot,tdrp,toolsa
  Searching dir:  libs/dsserver
running cmd: /home/meso/dev/lrose-core/codebase/make_bin/createMakefile.am.recurse.py --dir ./libs/dsserver
  Searching dir:  libs/dsserver/src
running cmd: /home/meso/dev/lrose-core/codebase/make_bin/createMakefile.am.lib.py --dir ./libs/dsserver --shared  --libList Mdv,dataport,didss,dsdata,dsserver,euclid,Fmq,physics,rapformats,rapmath,rapplot,tdrp,toolsa
  Searching dir:  libs/euclid
running cmd: /home/meso/dev/lrose-core/codebase/make_bin/createMakefile.am.recurse.py --dir ./libs/euclid
  Searching dir:  libs/euclid/src
running cmd: /home/meso/dev/lrose-core/codebase/make_bin/createMakefile.am.lib.py --dir ./libs/euclid --shared  --libList Mdv,dataport,didss,dsdata,dsserver,euclid,Fmq,physics,rapformats,rapmath,rapplot,tdrp,toolsa
  Searching dir:  libs/Fmq
running cmd: /home/meso/dev/lrose-core/codebase/make_bin/createMakefile.am.recurse.py --dir ./libs/Fmq
  Searching dir:  libs/Fmq/src
running cmd: /home/meso/dev/lrose-core/codebase/make_bin/createMakefile.am.lib.py --dir ./libs/Fmq --shared  --libList Mdv,dataport,didss,dsdata,dsserver,euclid,Fmq,physics,rapformats,rapmath,rapplot,tdrp,toolsa
  Searching dir:  libs/physics
running cmd: /home/meso/dev/lrose-core/codebase/make_bin/createMakefile.am.recurse.py --dir ./libs/physics
  Searching dir:  libs/physics/src
running cmd: /home/meso/dev/lrose-core/codebase/make_bin/createMakefile.am.lib.py --dir ./libs/physics --shared  --libList Mdv,dataport,didss,dsdata,dsserver,euclid,Fmq,physics,rapformats,rapmath,rapplot,tdrp,toolsa
  Searching dir:  libs/rapformats
running cmd: /home/meso/dev/lrose-core/codebase/make_bin/createMakefile.am.recurse.py --dir ./libs/rapformats
  Searching dir:  libs/rapformats/src
running cmd: /home/meso/dev/lrose-core/codebase/make_bin/createMakefile.am.lib.py --dir ./libs/rapformats --shared  --libList Mdv,dataport,didss,dsdata,dsserver,euclid,Fmq,physics,rapformats,rapmath,rapplot,tdrp,toolsa
  Searching dir:  libs/rapmath
running cmd: /home/meso/dev/lrose-core/codebase/make_bin/createMakefile.am.recurse.py --dir ./libs/rapmath
  Searching dir:  libs/rapmath/src
running cmd: /home/meso/dev/lrose-core/codebase/make_bin/createMakefile.am.lib.py --dir ./libs/rapmath --shared  --libList Mdv,dataport,didss,dsdata,dsserver,euclid,Fmq,physics,rapformats,rapmath,rapplot,tdrp,toolsa
  Searching dir:  libs/rapplot
running cmd: /home/meso/dev/lrose-core/codebase/make_bin/createMakefile.am.recurse.py --dir ./libs/rapplot
  Searching dir:  libs/rapplot/src
running cmd: /home/meso/dev/lrose-core/codebase/make_bin/createMakefile.am.lib.py --dir ./libs/rapplot --shared  --libList Mdv,dataport,didss,dsdata,dsserver,euclid,Fmq,physics,rapformats,rapmath,rapplot,tdrp,toolsa
  Searching dir:  libs/tdrp
running cmd: /home/meso/dev/lrose-core/codebase/make_bin/createMakefile.am.recurse.py --dir ./libs/tdrp
  Searching dir:  libs/tdrp/src
running cmd: /home/meso/dev/lrose-core/codebase/make_bin/createMakefile.am.lib.py --dir ./libs/tdrp --shared  --libList Mdv,dataport,didss,dsdata,dsserver,euclid,Fmq,physics,rapformats,rapmath,rapplot,tdrp,toolsa
  Searching dir:  libs/toolsa
running cmd: /home/meso/dev/lrose-core/codebase/make_bin/createMakefile.am.recurse.py --dir ./libs/toolsa
  Searching dir:  libs/toolsa/src
running cmd: /home/meso/dev/lrose-core/codebase/make_bin/createMakefile.am.lib.py --dir ./libs/toolsa --shared  --libList Mdv,dataport,didss,dsdata,dsserver,euclid,Fmq,physics,rapformats,rapmath,rapplot,tdrp,toolsa
  Searching dir:  apps
running cmd: /home/meso/dev/lrose-core/codebase/make_bin/createMakefile.am.recurse.py --dir ./apps
  Searching dir:  apps/tdrp
running cmd: /home/meso/dev/lrose-core/codebase/make_bin/createMakefile.am.recurse.py --dir ./apps/tdrp
  Searching dir:  apps/tdrp/src
running cmd: /home/meso/dev/lrose-core/codebase/make_bin/createMakefile.am.recurse.py --dir ./apps/tdrp/src
  Searching dir:  apps/tdrp/src/tdrp_gen
running cmd: /home/meso/dev/lrose-core/codebase/make_bin/createMakefile.am.app.radx.py --dir ./apps/tdrp/src/tdrp_gen --libList Mdv,dataport,didss,dsdata,dsserver,euclid,Fmq,physics,rapformats,rapmath,rapplot,tdrp,toolsa
  Searching dir:  apps/tdrp/src/tdrp_test
running cmd: /home/meso/dev/lrose-core/codebase/make_bin/createMakefile.am.app.radx.py --dir ./apps/tdrp/src/tdrp_test --libList Mdv,dataport,didss,dsdata,dsserver,euclid,Fmq,physics,rapformats,rapmath,rapplot,tdrp,toolsa
  Searching dir:  apps/tdrp/src/TdrpTest
running cmd: /home/meso/dev/lrose-core/codebase/make_bin/createMakefile.am.app.radx.py --dir ./apps/tdrp/src/TdrpTest --libList Mdv,dataport,didss,dsdata,dsserver,euclid,Fmq,physics,rapformats,rapmath,rapplot,tdrp,toolsa
  Searching dir:  apps/procmap
running cmd: /home/meso/dev/lrose-core/codebase/make_bin/createMakefile.am.recurse.py --dir ./apps/procmap
  Searching dir:  apps/procmap/src
running cmd: /home/meso/dev/lrose-core/codebase/make_bin/createMakefile.am.recurse.py --dir ./apps/procmap/src
  Searching dir:  apps/procmap/src/print_procmap
running cmd: /home/meso/dev/lrose-core/codebase/make_bin/createMakefile.am.app.radx.py --dir ./apps/procmap/src/print_procmap --libList Mdv,dataport,didss,dsdata,dsserver,euclid,Fmq,physics,rapformats,rapmath,rapplot,tdrp,toolsa
  Searching dir:  apps/procmap/src/procmap
running cmd: /home/meso/dev/lrose-core/codebase/make_bin/createMakefile.am.app.radx.py --dir ./apps/procmap/src/procmap --libList Mdv,dataport,didss,dsdata,dsserver,euclid,Fmq,physics,rapformats,rapmath,rapplot,tdrp,toolsa
  Searching dir:  apps/procmap/src/procmap_register
running cmd: /home/meso/dev/lrose-core/codebase/make_bin/createMakefile.am.app.radx.py --dir ./apps/procmap/src/procmap_register --libList Mdv,dataport,didss,dsdata,dsserver,euclid,Fmq,physics,rapformats,rapmath,rapplot,tdrp,toolsa
  Searching dir:  apps/procmap/src/procmap_unregister
running cmd: /home/meso/dev/lrose-core/codebase/make_bin/createMakefile.am.app.radx.py --dir ./apps/procmap/src/procmap_unregister --libList Mdv,dataport,didss,dsdata,dsserver,euclid,Fmq,physics,rapformats,rapmath,rapplot,tdrp,toolsa
  Searching dir:  apps/procmap/src/scripts
  Ignoring dir: apps/procmap/src/scripts
  Searching dir:  apps/procmap/src/test_procmap
running cmd: /home/meso/dev/lrose-core/codebase/make_bin/createMakefile.am.app.radx.py --dir ./apps/procmap/src/test_procmap --libList Mdv,dataport,didss,dsdata,dsserver,euclid,Fmq,physics,rapformats,rapmath,rapplot,tdrp,toolsa
  Searching dir:  apps/spdb_utils
running cmd: /home/meso/dev/lrose-core/codebase/make_bin/createMakefile.am.recurse.py --dir ./apps/spdb_utils
  Searching dir:  apps/spdb_utils/src
running cmd: /home/meso/dev/lrose-core/codebase/make_bin/createMakefile.am.recurse.py --dir ./apps/spdb_utils/src
  Searching dir:  apps/spdb_utils/src/AcPolygonStats
running cmd: /home/meso/dev/lrose-core/codebase/make_bin/createMakefile.am.app.radx.py --dir ./apps/spdb_utils/src/AcPolygonStats --libList Mdv,dataport,didss,dsdata,dsserver,euclid,Fmq,physics,rapformats,rapmath,rapplot,tdrp,toolsa
  Searching dir:  apps/spdb_utils/src/AdvectPolygon
running cmd: /home/meso/dev/lrose-core/codebase/make_bin/createMakefile.am.app.radx.py --dir ./apps/spdb_utils/src/AdvectPolygon --libList Mdv,dataport,didss,dsdata,dsserver,euclid,Fmq,physics,rapformats,rapmath,rapplot,tdrp,toolsa
  Searching dir:  apps/spdb_utils/src/AverageSpdbSndg
running cmd: /home/meso/dev/lrose-core/codebase/make_bin/createMakefile.am.app.radx.py --dir ./apps/spdb_utils/src/AverageSpdbSndg --libList Mdv,dataport,didss,dsdata,dsserver,euclid,Fmq,physics,rapformats,rapmath,rapplot,tdrp,toolsa
  Searching dir:  apps/spdb_utils/src/FixStationAltitudes
running cmd: /home/meso/dev/lrose-core/codebase/make_bin/createMakefile.am.app.radx.py --dir ./apps/spdb_utils/src/FixStationAltitudes --libList Mdv,dataport,didss,dsdata,dsserver,euclid,Fmq,physics,rapformats,rapmath,rapplot,tdrp,toolsa
  Searching dir:  apps/spdb_utils/src/GenPoly2Mdv
running cmd: /home/meso/dev/lrose-core/codebase/make_bin/createMakefile.am.app.radx.py --dir ./apps/spdb_utils/src/GenPoly2Mdv --libList Mdv,dataport,didss,dsdata,dsserver,euclid,Fmq,physics,rapformats,rapmath,rapplot,tdrp,toolsa
  Searching dir:  apps/spdb_utils/src/Hash
running cmd: /home/meso/dev/lrose-core/codebase/make_bin/createMakefile.am.app.radx.py --dir ./apps/spdb_utils/src/Hash --libList Mdv,dataport,didss,dsdata,dsserver,euclid,Fmq,physics,rapformats,rapmath,rapplot,tdrp,toolsa
  Searching dir:  apps/spdb_utils/src/NetCDF2Spdb
running cmd: /home/meso/dev/lrose-core/codebase/make_bin/createMakefile.am.app.radx.py --dir ./apps/spdb_utils/src/NetCDF2Spdb --libList Mdv,dataport,didss,dsdata,dsserver,euclid,Fmq,physics,rapformats,rapmath,rapplot,tdrp,toolsa
  Searching dir:  apps/spdb_utils/src/PrintGenPt1D
running cmd: /home/meso/dev/lrose-core/codebase/make_bin/createMakefile.am.app.radx.py --dir ./apps/spdb_utils/src/PrintGenPt1D --libList Mdv,dataport,didss,dsdata,dsserver,euclid,Fmq,physics,rapformats,rapmath,rapplot,tdrp,toolsa
  Searching dir:  apps/spdb_utils/src/PrintHydroStation
running cmd: /home/meso/dev/lrose-core/codebase/make_bin/createMakefile.am.app.radx.py --dir ./apps/spdb_utils/src/PrintHydroStation --libList Mdv,dataport,didss,dsdata,dsserver,euclid,Fmq,physics,rapformats,rapmath,rapplot,tdrp,toolsa
  Searching dir:  apps/spdb_utils/src/PrintSigAirMet
running cmd: /home/meso/dev/lrose-core/codebase/make_bin/createMakefile.am.app.radx.py --dir ./apps/spdb_utils/src/PrintSigAirMet --libList Mdv,dataport,didss,dsdata,dsserver,euclid,Fmq,physics,rapformats,rapmath,rapplot,tdrp,toolsa
  Searching dir:  apps/spdb_utils/src/PrintSpdbMetar
running cmd: /home/meso/dev/lrose-core/codebase/make_bin/createMakefile.am.app.radx.py --dir ./apps/spdb_utils/src/PrintSpdbMetar --libList Mdv,dataport,didss,dsdata,dsserver,euclid,Fmq,physics,rapformats,rapmath,rapplot,tdrp,toolsa
  Searching dir:  apps/spdb_utils/src/Rhi2Spdb
running cmd: /home/meso/dev/lrose-core/codebase/make_bin/createMakefile.am.app.radx.py --dir ./apps/spdb_utils/src/Rhi2Spdb --libList Mdv,dataport,didss,dsdata,dsserver,euclid,Fmq,physics,rapformats,rapmath,rapplot,tdrp,toolsa
  Searching dir:  apps/spdb_utils/src/Sigmet2Mdv
running cmd: /home/meso/dev/lrose-core/codebase/make_bin/createMakefile.am.app.radx.py --dir ./apps/spdb_utils/src/Sigmet2Mdv --libList Mdv,dataport,didss,dsdata,dsserver,euclid,Fmq,physics,rapformats,rapmath,rapplot,tdrp,toolsa
  Searching dir:  apps/spdb_utils/src/Sndg2Ascii
running cmd: /home/meso/dev/lrose-core/codebase/make_bin/createMakefile.am.app.radx.py --dir ./apps/spdb_utils/src/Sndg2Ascii --libList Mdv,dataport,didss,dsdata,dsserver,euclid,Fmq,physics,rapformats,rapmath,rapplot,tdrp,toolsa
  Searching dir:  apps/spdb_utils/src/SpdbBdry2Axf
running cmd: /home/meso/dev/lrose-core/codebase/make_bin/createMakefile.am.app.radx.py --dir ./apps/spdb_utils/src/SpdbBdry2Axf --libList Mdv,dataport,didss,dsdata,dsserver,euclid,Fmq,physics,rapformats,rapmath,rapplot,tdrp,toolsa
  Searching dir:  apps/spdb_utils/src/SpdbMultSim
running cmd: /home/meso/dev/lrose-core/codebase/make_bin/createMakefile.am.app.radx.py --dir ./apps/spdb_utils/src/SpdbMultSim --libList Mdv,dataport,didss,dsdata,dsserver,euclid,Fmq,physics,rapformats,rapmath,rapplot,tdrp,toolsa
  Searching dir:  apps/spdb_utils/src/StationCompare
running cmd: /home/meso/dev/lrose-core/codebase/make_bin/createMakefile.am.app.radx.py --dir ./apps/spdb_utils/src/StationCompare --libList Mdv,dataport,didss,dsdata,dsserver,euclid,Fmq,physics,rapformats,rapmath,rapplot,tdrp,toolsa
  Searching dir:  apps/spdb_utils/src/extractStationLocationList
running cmd: /home/meso/dev/lrose-core/codebase/make_bin/createMakefile.am.app.radx.py --dir ./apps/spdb_utils/src/extractStationLocationList --libList Mdv,dataport,didss,dsdata,dsserver,euclid,Fmq,physics,rapformats,rapmath,rapplot,tdrp,toolsa
  Searching dir:  apps/spdb_utils/src/run_PrintSigAirMet
running cmd: /home/meso/dev/lrose-core/codebase/make_bin/createMakefile.am.app.radx.py --dir ./apps/spdb_utils/src/run_PrintSigAirMet --libList Mdv,dataport,didss,dsdata,dsserver,euclid,Fmq,physics,rapformats,rapmath,rapplot,tdrp,toolsa
ERROR -  createMakefile.am.app.radx.py
  Cannot find TARGET_FILE in  __makefile.template
  dir:  ./apps/spdb_utils/src/run_PrintSigAirMet
Traceback (most recent call last):
  File "./make_bin/createConfigure.am.py", line 475, in <module>
    main()
  File "./make_bin/createConfigure.am.py", line 98, in main
    searchDir(appsDir)
  File "./make_bin/createConfigure.am.py", line 259, in searchDir
    searchDir(subdirPath)
  File "./make_bin/createConfigure.am.py", line 259, in searchDir
    searchDir(subdirPath)
  File "./make_bin/createConfigure.am.py", line 259, in searchDir
    searchDir(subdirPath)
  File "./make_bin/createConfigure.am.py", line 246, in searchDir
    runCommand(cmd)
  File "./make_bin/createConfigure.am.py", line 460, in runCommand
    retcode = subprocess.check_call(cmd, shell=True)
  File "/usr/lib64/python2.7/subprocess.py", line 186, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '/home/meso/dev/lrose-core/codebase/make_bin/createMakefile.am.app.radx.py --dir ./apps/spdb_utils/src/run_PrintSigAirMet --libList Mdv,dataport,didss,dsdata,dsserver,euclid,Fmq,physics,rapformats,rapmath,rapplot,tdrp,toolsa' returned non-zero exit status 1
Running build_lrose
  package: radx
  prefix: /home/meso/lrose
  runDir: /home/meso/dev/lrose-core
package = radx
./build/build_lrose: line 140: ./configure: No such file or directory
Options:
  Debug:  True
  Verbose:  False
  binDir:  /home/meso/lrose/bin
  relDir:  radx_runtime_libs
  isOsx:  False
  ignore:  libc.so,libpthread.so,libdl.so
  ignoreList:  ['libc.so', 'libpthread.so', 'libdl.so']
------------------------------------------------
====>> binPathList: 
====>> nBins:  20
   /home/meso/lrose/bin/h5repack
   /home/meso/lrose/bin/h5copy
   /home/meso/lrose/bin/h5import
   /home/meso/lrose/bin/h5debug
   /home/meso/lrose/bin/h5jam
   /home/meso/lrose/bin/gif2h5
   /home/meso/lrose/bin/h5diff
   /home/meso/lrose/bin/ncgen
   /home/meso/lrose/bin/h5stat
   /home/meso/lrose/bin/h5repart
   /home/meso/lrose/bin/h5dump
   /home/meso/lrose/bin/udunits2
   /home/meso/lrose/bin/h52gif
   /home/meso/lrose/bin/ncdump
   /home/meso/lrose/bin/h5mkgrp
   /home/meso/lrose/bin/h5perf_serial
   /home/meso/lrose/bin/h5ls
   /home/meso/lrose/bin/ncgen3
   /home/meso/lrose/bin/h5unjam
   /home/meso/lrose/bin/nccopy
------------------------------------------------
------------------------------------------------
====>> dictionary of all libs: 
====>> nLibs:  7
   libhdf5_hl.so.10 , /home/meso/lrose/lib/libhdf5_hl.so.10
   libudunits2.so.0 , /home/meso/lrose/lib/libudunits2.so.0
   libnetcdf.so.11 , /home/meso/lrose/lib/libnetcdf.so.11
   libz.so.1 , /lib64/libz.so.1
   libhdf5.so.10 , /home/meso/lrose/lib/libhdf5.so.10
   libm.so.6 , /lib64/libm.so.6
   libexpat.so.1 , /lib64/libexpat.so.1
------------------------------------------------
===>>> Copying lib:  /home/meso/lrose/lib/libhdf5_hl.so.10
                to:  /home/meso/lrose/bin/radx_runtime_libs
===>>> Copying lib:  /home/meso/lrose/lib/libudunits2.so.0
                to:  /home/meso/lrose/bin/radx_runtime_libs
===>>> Copying lib:  /home/meso/lrose/lib/libnetcdf.so.11
                to:  /home/meso/lrose/bin/radx_runtime_libs
===>>> Copying lib:  /lib64/libz.so.1
                to:  /home/meso/lrose/bin/radx_runtime_libs
===>>> Copying lib:  /home/meso/lrose/lib/libhdf5.so.10
                to:  /home/meso/lrose/bin/radx_runtime_libs
===>>> Copying lib:  /lib64/libm.so.6
                to:  /home/meso/lrose/bin/radx_runtime_libs
===>>> Copying lib:  /lib64/libexpat.so.1
                to:  /home/meso/lrose/bin/radx_runtime_libs

============= Checking libs for radx =============
==================>> ERROR <<====================
=====>> INCOMPLETE radx LIBS INSTALLATION <<====
  n libraries missing: 14
    missing lib: libFmq.a
    missing lib: libMdv.a
    missing lib: libRadx.a
    missing lib: libSpdb.a
    missing lib: libdataport.a
    missing lib: libdidss.a
    missing lib: libdsserver.a
    missing lib: libeuclid.a
    missing lib: libkd.a
    missing lib: libradar.a
    missing lib: librapformats.a
    missing lib: librapmath.a
    missing lib: libtdrp.a
    missing lib: libtoolsa.a
=================================================
====================================================

============= checking apps for radx =============
==================>> ERROR <<====================
=====>> INCOMPLETE radx APPS INSTALLATION <<====
  n applications missing: 14
    missing app: /home/meso/lrose/bin/Dsr2Radx
    missing app: /home/meso/lrose/bin/FixCfradialPaths
    missing app: /home/meso/lrose/bin/FixRadxPointing
    missing app: /home/meso/lrose/bin/Radx2Dsr
    missing app: /home/meso/lrose/bin/Radx2Grid
    missing app: /home/meso/lrose/bin/RadxBeamBlock
    missing app: /home/meso/lrose/bin/RadxCheck
    missing app: /home/meso/lrose/bin/RadxConvert
    missing app: /home/meso/lrose/bin/RadxCov2Mom
    missing app: /home/meso/lrose/bin/RadxMergeFields
    missing app: /home/meso/lrose/bin/RadxMon
    missing app: /home/meso/lrose/bin/RadxPartRain
    missing app: /home/meso/lrose/bin/RadxPrint
    missing app: /home/meso/lrose/bin/tdrp_gen
=================================================
==================================================
`

**Comment by yuxxer49** [comment]
I have the exact same problem, I reverted to 30f345cb89891820a44e5586356e0432f8e1a65f and everything built ok.

**Comment by joshuass** [comment]
@mike-dixon Hi Mike, any ideas why I might be getting these build errors?

**Comment by mike-dixon** [comment]
I took a look at that error you are getting.

Were you building lrose or radx?

We did have some problems with commit 02c96b4, just after 30f345, and fixed some file-specific commits after that.

Looking at the error messages I am puzzled about why it would try to compile run_PrintSigAirMet, which is a perl script and is not in the build. There is a default 'Makefile' in the spdb_utils/src directory which appeared to be invoked in this case. I cleaned up that Makefile just in case it is being used.

Can you please try again and see how you go?

Thanks

Mike

**Comment by joshuass** [comment]
Hi Mike,
I've had to rebuild my machine and now stuck with a different problem (likely due to using Ubuntu 18.04)
./configure: line 20906: syntax error near unexpected token `QT,'
./configure: line 20906: `PKG_CHECK_MODULES(QT, Qt5Core Qt5Widgets Qt5Gui Qt5Network, HAVE_QT="yes", HAVE_QT="no")'

I might just use a VM. Do you recommend a specific OS/version?

**Comment by burghart** [comment]
Hi Josh,

As of now, we build LROSE most frequently under CentOS 7, so that would be
your best bet for a VM.

Chris

**Comment by burghart** [comment]
Joshua,

Apologies for my familiarity in the previous comment. I know a number of Joshuas who all go by Josh, and just typed that out of habit...

**Comment by joshuass** [comment]
Thanks for the response. No issues!
