### ISSUE TITLE
MDV in TITAN Assistance

### ISSUE THREAD

**Issue by toddstellies** [NCAR/lrose-core#55]
Would anyone be so kind as to share code (for LINUX Ubuntu OS, using csh) to open an '.mdv' file from start to a graphical representation of the radar image (TITAN display). 

https://drive.google.com/open?id=1MZhTfe0HtTUUQhg1wXg6XInMNrbH0Gk0

The drive link above consists of an '.mdv' file; and the output image that I want to arrive at. 

Thank you so much

**Comment by mike-dixon** [comment]
Take a look at the docs in:

  https://github.com/NCAR/lrose-titan
