### ISSUE TITLE
Add I/O streaming to LROSE tools

### ISSUE THREAD

**Issue by leavesntwigs** [NCAR/lrose-core#67]
It would be nice to avoid writing intermediate data files and instead stream the data from one LROSE tool into the next tool.  For example, Linux piping would be nice, particularly for large data sets.

**Comment by nguy** [comment]
I agree that this would be a nice feature

**Comment by leavesntwigs** [comment]
This data pipeline philosophy will probably be implemented in the new Science Gateway that is in development.  The intermediate data file management will be hidden to the user, but available if needed.
