### ISSUE TITLE
RadxConvert not outputting cfradial 2 

### ISSUE THREAD

**Issue by ChrisAlphabet** [NCAR/lrose-core#70]
I can't get RadxConvert to output in cfradial 2 format. When I run 

```
 RadxConvert -cf2 -f 02_20190307_002432.pvol.h5
```

I get the error message

```
terminate called after throwing an instance of 'NcxxAttMeta'
  what():  NetCDF: Can't open HDF5 attribute
file: Ncxx/NcxxFile.cc  line:88
Aborted (core dumped)
```

I have the same error whether I use an odim_hdf5 file or a nexrad file.

Converting to the default cfradial works, so perhaps my system is missing something?

I installed lrose-core using the .deb package and am running ubuntu in a virtual machine.

Any help would be greatly appreciated!

**Comment by mike-dixon** [comment]
The CfRadial standard is a bit in flux at the moment.
We will get full CfRadial2 support in RadxConvert by mid-2020.
Until then it is better to use CfRadial 1.4.

**Comment by mike-dixon** [comment]
Keeping it open as a reminder for now.

**Comment by mike-dixon** [comment]
The latest release of lrose-core tests OK in writing CfRadial2 files.
See https://github.com/NCAR/lrose-core/releases
