### ISSUE TITLE
Error found in NCAR build environment documentation

### ISSUE THREAD

**Issue by danielhogg** [NCAR/lrose-core#72]
I was setting up the [NCAR build environment](https://github.com/NCAR/lrose-core/blob/master/docs/build/NCAR_build_environment.linux.md), and the overall process was failing on the following step:
```bash
cd $LROSE_CORE_DIR/codebase
./make_bin/install_package_makefiles.py
```
After some digging, I found out that there were two problems:

1. The documentation refers to install_package_makefiles.py, but the [latest file](https://github.com/NCAR/lrose-core/blob/master/codebase/make_bin/installPackageMakefiles.py) is now titled "installPackageMakefiles.py".
2. For some reason, I had to change the command so that it was executed from within $LROSE_CORE_DIR, not the codebase subdirectory.

I used these following steps instead, and it allowed me to build successfully.
```bash
cd $LROSE_CORE_DIR
./codebase/make_bin/installPackageMakefiles.py
```
It would be great to update the documentation to reflect these steps.

**Comment by danielhogg** [comment]
Another thing I noticed was that the make argument 'opt' can be substituted for 'dbgopt', and it generates all the debug symbols required for GDB debugging. This was pretty useful and I think it would be a good side-note to add to the [NCAR build environment docs](https://github.com/NCAR/lrose-core/blob/master/docs/build/NCAR_build_environment.linux.md).

**Comment by mike-dixon** [comment]
Fixed - thank you for the issue - Mike
