### ISSUE TITLE
LROSE Install Issues on NERC's JASMIN

### ISSUE THREAD

**Issue by rrniii** [NCAR/lrose-core#75]
Hello All,

I have been trying to install lrose on our shared HPC and I keep getting the errors below.

I have followed the directions here:

https://github.com/NCAR/lrose-core/blob/master/docs/download/clone_src_and_build.linux.md

Our system is Lentos so I following the RedHat instructions but I am unable to do the two yum installs as I am not allowed root permissions.

I have also tried the non-git way (https://github.com/NCAR/lrose-core/blob/master/docs/download/download_src_and_build.linux.md) and got similar errors when it came to the make.

I have looked at the log files but cannot sort out what is the issue.

Please advise.

Cheers, Neely 

  Cannot open file: makefile
ERROR -  checkout_and_build_auto.py
  Cannot open file: makefile
ERROR -  checkout_and_build_auto.py
  Cannot open file: makefile
========================= setup-autoconf =========================
====>> Creating log file: /gws/smf/j04/ncas_radar/software/lrose_build/logs/setup-autoconf.log <<==
Running cmd: ./make_bin/createConfigure.am.py --dir . --baseName configure.base.shared --shared --pkg lrose-radx --verbose 
Log file is: /gws/smf/j04/ncas_radar/software/lrose_build/logs/setup-autoconf.log
    ....
Child returned code:  0
    done
========================= create-qt-moc-files =========================
====>> Creating log file: /gws/smf/j04/ncas_radar/software/lrose_build/logs/create-qt-moc-files.log <<==
========================= build-netcdf =========================
====>> Creating log file: /gws/smf/j04/ncas_radar/software/lrose_build/logs/build-netcdf.log <<==
Running cmd: ./build_and_install_netcdf -x /gws/smf/j04/ncas_radar/software/lrose_build/scratch
Log file is: /gws/smf/j04/ncas_radar/software/lrose_build/logs/build-netcdf.log
    ....
Child returned code:  0
    done
========================= print-environment =========================
====>> Creating log file: /gws/smf/j04/ncas_radar/software/lrose_build/logs/print-environment.log <<==
Running cmd: env
Log file is: /gws/smf/j04/ncas_radar/software/lrose_build/logs/print-environment.log
    ....
Child returned code:  0
    done
========================= run-configure =========================
====>> Creating log file: /gws/smf/j04/ncas_radar/software/lrose_build/logs/run-configure.log <<==
Running cmd: ./configure --with-hdf5=/gws/smf/j04/ncas_radar/software/lrose_build/scratch --with-netcdf=/gws/smf/j04/ncas_radar/software/lrose_build/scratch --prefix=/gws/smf/j04/ncas_radar/software/lrose_build/scratch
Log file is: /gws/smf/j04/ncas_radar/software/lrose_build/logs/run-configure.log
    ....
Traceback (most recent call last):
  File "./checkout_and_build_auto.py", line 816, in <module>
    main()
  File "./checkout_and_build_auto.py", line 269, in main
    buildPackage()
  File "./checkout_and_build_auto.py", line 601, in buildPackage
    shellCmd(cmd)
  File "./checkout_and_build_auto.py", line 799, in shellCmd
    retcode = subprocess.check_call(cmdToRun, shell=True)
  File "/usr/lib64/python2.6/subprocess.py", line 505, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command './configure --with-hdf5=/gws/smf/j04/ncas_radar/software/lrose_build/scratch --with-netcdf=/gws/smf/j04/ncas_radar/software/lrose_build/scratch --prefix=/gws/smf/j04/ncas_radar/software/lrose_build/scratch 1>> /gws/smf/j04/ncas_radar/software/lrose_build/logs/run-configure.log 2>&1' returned non-zero exit status 1

**Comment by mjskier** [comment]
Each step of the build creates its own log file. So for a more detailed error of what went wrong, look in
Log file is: **/gws/smf/j04/ncas_radar/software/lrose_build/logs/run-configure.log**

My guess is that you are missing dependencies since you were not able to run the 2 yums commands.

**Comment by mike-dixon** [comment]
Sent an email directly to Ryan Neely at NCAS.
New LROSE version is available.
