### ISSUE TITLE
RPM probably unnecessarily requires devel packages

### ISSUE THREAD

**Issue by alaniwi** [NCAR/lrose-core#76]
The RPM has a lot of `*-devel` requirements, forcing installation of a lot of devel packages which might not be needed at run-time.

For example:

https://github.com/NCAR/lrose-core/blob/d524de13628e33f40d2f9eb7067b10e2b2ae49d9/build/packages/redhat/rpm.spec.body#L19

Probably in this example, the requirement could be replaced with:

```
Requires: libX11
BuildRequires: libX11-devel
```

Then the the devel packages must be installed on the machine on which the RPM is built, but not every machine on which it is subsequently installed.

**Comment by mjskier** [comment]
This is correct. When building a docker image for lrose-blaze I only include the needed runtime libraries, not the devel ones.
[Ubuntu 18.10 Dockerfile](https://github.com/nsf-lrose/release-tools/blob/master/lrose-docker-scripts/Dockerfile_18.10)
