### ISSUE TITLE
Error When Installing

### ISSUE THREAD

**Issue by WeatherQueen** [NCAR/lrose-core#85]
Hello,

I'm trying to install  the lrose-core on my Ubuntu system with the end goal of being able to use Titan. I followed the instructions on installing and checking the dependencies that you posted.

When attempting to install the core I keep getting the following error in the command line:

========================= build-apps =========================
Running cmd: make -k -j 8
Log file is: /tmp/lrose_build/logs/build-apps.log
    ....
Traceback (most recent call last):
  File "./checkout_and_build_auto.py", line 1082, in <module>
    main()
  File "./checkout_and_build_auto.py", line 304, in main
    buildPackage()
  File "./checkout_and_build_auto.py", line 687, in buildPackage
    shellCmd(cmd)
  File "./checkout_and_build_auto.py", line 1065, in shellCmd
    retcode = subprocess.check_call(cmdToRun, shell=True)
  File "/home/2r2/anaconda3/lib/python3.7/subprocess.py", line 347, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'make -k -j 8 1>> /tmp/lrose_build/logs/build-apps.log 2>&1' returned non-zero exit status 2.

When I check the run-configure.log there is no error kick back. In the build-apps.log I get the following error for each package build:
collect2: error: ld returned 1 exit status
makefile:541: recipe for target 'Rview' failed
make[3]: *** [Rview] Error 1
make[3]: Target 'all' not remade because of errors.

Any help would be much appreciated.

WxQ

**Comment by mike-dixon** [comment]
Hi WxQ
We have significantly updated and simplified the build procedure.
We made a new release on 20200701.
Can you try that?
Thanks
Mike
