### ISSUE TITLE
RadxConvert param output_filename not working

### ISSUE THREAD

**Issue by ShaneEEEE** [NCAR/lrose-core#86]
When output_filename_mode is set to SPECIFY_FILE_NAME and setting output_filename to any combination of file names, an error is produced

`ERROR - RadxConvert::_writeVol
  Cannot write file to path: /var/www/html/data/volOdimH5/01_20201010_004000_SUR.h5
ERROR - RadxFile::writeToPath
  File format not recognized: 14

ERROR - RadxConvert::_runFileList
  Cannot write aggregated volume to file
RadxConvert done
====>> n good files processed: 1
ERROR - running RadxConvert
`

Param File:
`debug = DEBUG_VERBOSE;
instance = "convertToOdim";
mode = FILELIST;
set_fixed_angle_limits = FALSE;
read_set_radar_num = FALSE;
aggregate_all_files_on_read = TRUE;
ignore_idle_scan_mode_on_read = TRUE;
remove_rays_with_all_data_missing = TRUE;
clear_transition_flag_on_all_rays = FALSE;
remove_rays_with_antenna_transitions = FALSE;
trim_surveillance_sweeps_to_360deg = FALSE;
preserve_sweeps = FALSE;
remove_long_range_rays = TRUE;
remove_short_range_rays = FALSE;
set_ngates_constant = FALSE;
remap_to_predominant_range_geometry = FALSE;
remap_to_finest_range_geometry = FALSE;
override_start_range = FALSE;
override_instrument_name = FALSE;
override_volume_number = FALSE;
override_radar_location = FALSE;
change_radar_latitude_sign = TRUE;
apply_georeference_corrections = FALSE;
apply_time_offset = FALSE;
apply_azimuth_offset = FALSE;
azimuth_offset = 0;
apply_elevation_offset = FALSE;
override_instrument_type = FALSE;
override_platform_type = FALSE;
override_primary_axis = FALSE;
override_beam_width = FALSE;
override_antenna_gain = FALSE;

reload_sweep_info_from_rays = TRUE;
reload_volume_info_from_rays = FALSE;
recompute_sweep_fixed_angles = FALSE;
optimize_surveillance_transitions = FALSE;

adjust_sweep_limits_using_angles = FALSE;
sort_sweeps_by_fixed_angle = TRUE;

set_output_fields = TRUE;

output_fields = {
  {
    input_field_name = "Refl",
    output_field_name = "Refl",
    long_name = "reflectivity",
    standard_name = "equivalent_reflectivity_factor",
    output_units = "dBZ",
    encoding = OUTPUT_ENCODING_INT08,
    output_scaling = SCALING_SPECIFIED,
    output_scale = 0.5,
    output_offset = -32
  }
  ,
  {
    input_field_name = "Vel",
    output_field_name = "Vel",
    long_name = "radial_velocity",
    standard_name = "radial_velocity_of_scatterers_away_from_instrument",
    output_units = "m/s",
    encoding = OUTPUT_ENCODING_INT08,
    output_scaling = SCALING_SPECIFIED,
    output_scale = 0.336574,
    output_offset = -27.094206
  }
};

write_other_fields_unchanged = FALSE;
exclude_specified_fields = FALSE;
set_output_encoding_for_all_fields = FALSE;
apply_censoring = FALSE;

apply_linear_transforms = FALSE;

apply_variable_transforms = FALSE;
output_format = OUTPUT_FORMAT_ODIM_HDF5;
output_native_byte_order = FALSE;

output_dir = "/var/www/html/data/volOdimH5";
output_filename_mode = SPECIFY_FILE_NAME;
output_filename = "01_20201010_004500_SUR.h5";
include_instrument_name_in_file_name = FALSE;
include_site_name_in_file_name = FALSE;
include_subsecs_in_file_name = FALSE;
include_scan_type_in_file_name = FALSE;
include_vol_num_in_file_name = FALSE;
use_hyphen_in_file_name_datetime_part = FALSE;
append_day_dir_to_output_dir = FALSE;
append_year_dir_to_output_dir = FALSE;
write_individual_sweeps = FALSE;
write_latest_data_info = FALSE;
write_using_proposed_standard_name_attr = FALSE;
separate_output_dirs_by_scan_type = FALSE;
override_missing_metadata_values = FALSE;
override_missing_field_values = TRUE;
missing_field_si08 = 0;`

**Comment by mike-dixon** [comment]
This works correctly in the latest release, 20221229.
