### ISSUE TITLE
brew install lrose-core.rb (202007XX version) ruby errors

### ISSUE THREAD

**Issue by leavesntwigs** [NCAR/lrose-core#88]
brew install lrose-core.rb (202007XX version) 
(running 10.15 Catalina),  two errors occurred (see below).  I was running as lroot in both cases.

brew install lrose-core.rb
Traceback (most recent call last):
        17: from /usr/local/Homebrew/Library/Homebrew/brew.rb:30:in `<main>'
        16: from /usr/local/Homebrew/Library/Homebrew/brew.rb:30:in `require_relative'
 ...
         2: from /usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/concurrent-ruby-1.1.7/lib/concurrent-ruby/concurrent/utility/native_extension_loader.rb:62:in `try_load_c_extension'
         1: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- concurrent/2.6/concurrent_ruby_ext (LoadError)
        28: from /usr/local/Homebrew/Library/Homebrew/brew.rb:30:in `<main>'
        27: from /usr/local/Homebrew/Library/Homebrew/brew.rb:30:in `require_relative'
  ...
         2: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/bundler_version_finder.rb:68:in `lockfile_version'
         1: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/bundler_version_finder.rb:80:in `lockfile_contents'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/bundler_version_finder.rb:80:in `pwd': No such file or directory - getcwd (Errno::ENOENT)

**Comment by mike-dixon** [comment]
This problem has been resolved in later versions of OSX.
It does not occur with monterey and ventura.
