### ISSUE TITLE
homebrew lrose-core.rb install fails from x11 issues 

### ISSUE THREAD

**Issue by jmarpn** [NCAR/lrose-core#90]
I'm trying to install lrose-core.rb on mac Catalina (also fails on Mojave). I have a fresh installation of quartz. It seems to be choking on x11 related issues. 

brew install lrose-core.rb 

Updating Homebrew...
==> Auto-updated Homebrew!
Updated 2 taps (homebrew/core and homebrew/cask).
==> New Formulae
crane                        crcany                       hexo                         ko                           vsh
==> Updated Formulae
Updated 282 formulae.
==> Renamed Formulae
prest -> prestd
==> New Casks
f-bar                                                                    ptpwebcam
lightkey                                                                 the-unofficial-homestuck-collection
==> Updated Casks
Updated 133 casks.
==> Deleted Casks
aegisub                        teamspeak-client

Warning: Calling depends_on :x11 is deprecated! Use depends_on specific X11 formula(e) instead.
==> Downloading https://homebrew.bintray.com/bottles/cmake-3.19.3.catalina.bottle.tar.gz
Already downloaded: /Users/marq789/Library/Caches/Homebrew/downloads/97957bfe5f617c8d884429e1bc2f4c2533cafb17c6a4132917062335c96c0e29--cmake-3.19.3.catalina.bottle.tar.gz
==> Downloading https://github.com/NCAR/lrose-core/releases/download/lrose-core-20200701/lrose-core-20200719.src.mac_osx.tgz
Already downloaded: /Users/marq789/Library/Caches/Homebrew/downloads/305606d0fc2ec4100e589eaf0aeac05067c7fc37e4b8fca063d998220fd42e76--lrose-core-20200719.src.mac_osx.tgz
==> Installing dependencies for lrose-core: cmake
==> Installing lrose-core dependency: cmake
==> Pouring cmake-3.19.3.catalina.bottle.tar.gz
==> Caveats
Emacs Lisp files have been installed to:
  /usr/local/share/emacs/site-lisp/cmake
==> Summary
🍺  /usr/local/Cellar/cmake/3.19.3: 6,376 files, 63.9MB
==> Installing lrose-core
Warning: Calling depends_on :x11 is deprecated! Use depends_on specific X11 formula(e) instead.
==> ./configure --prefix=/usr/local/Cellar/lrose-core/core-20200719
==> make install
Last 15 lines from /Users/marq789/Library/Logs/Homebrew/lrose-core/02.make:
libtool: compile:  clang -DHAVE_CONFIG_H -I. -I../../.. -DNO_JASPER_LIB -I./include -fPIC -I/usr/X11R6/include -I/opt/X11/include -I../../FiltAlg/src/include -I../../FiltAlgVirtVol/src/include -I../../Fmq/src/include -I../../Mdv/src/include -I../../Ncxx/src/include -I../../Radx/src/include -I../../Refract/src/include -I../../Spdb/src/include -I../../advect/src/include -I../../cidd/src/include -I../../contour/src/include -I../../dataport/src/include -I../../didss/src/include -I../../dsdata/src/include -I../../dsserver/src/include -I../../euclid/src/include -I../../grib/src/include -I../../grib2/src/include -I../../hydro/src/include -I../../kd/src/include -I../../physics/src/include -I../../radar/src/include -I../../rapformats/src/include -I../../rapmath/src/include -I../../rapplot/src/include -I../../shapelib/src/include -I../../tdrp/src/include -I../../titan/src/include -I../../toolsa/src/include -g -O2 -c cdata_util/cdata_util.c -o cdata_util/cdata_util.o >/dev/null 2>&1
libtool: compile:  clang -DHAVE_CONFIG_H -I. -I../../.. -DNO_JASPER_LIB -I./include -fPIC -I/usr/X11R6/include -I/opt/X11/include -I../../FiltAlg/src/include -I../../FiltAlgVirtVol/src/include -I../../Fmq/src/include -I../../Mdv/src/include -I../../Ncxx/src/include -I../../Radx/src/include -I../../Refract/src/include -I../../Spdb/src/include -I../../advect/src/include -I../../cidd/src/include -I../../contour/src/include -I../../dataport/src/include -I../../didss/src/include -I../../dsdata/src/include -I../../dsserver/src/include -I../../euclid/src/include -I../../grib/src/include -I../../grib2/src/include -I../../hydro/src/include -I../../kd/src/include -I../../physics/src/include -I../../radar/src/include -I../../rapformats/src/include -I../../rapmath/src/include -I../../rapplot/src/include -I../../shapelib/src/include -I../../tdrp/src/include -I../../titan/src/include -I../../toolsa/src/include -g -O2 -c cdata_util/latlon2xy.c  -fno-common -DPIC -o cdata_util/.libs/latlon2xy.o
libtool: compile:  clang -DHAVE_CONFIG_H -I. -I../../.. -DNO_JASPER_LIB -I./include -fPIC -I/usr/X11R6/include -I/opt/X11/include -I../../FiltAlg/src/include -I../../FiltAlgVirtVol/src/include -I../../Fmq/src/include -I../../Mdv/src/include -I../../Ncxx/src/include -I../../Radx/src/include -I../../Refract/src/include -I../../Spdb/src/include -I../../advect/src/include -I../../cidd/src/include -I../../contour/src/include -I../../dataport/src/include -I../../didss/src/include -I../../dsdata/src/include -I../../dsserver/src/include -I../../euclid/src/include -I../../grib/src/include -I../../grib2/src/include -I../../hydro/src/include -I../../kd/src/include -I../../physics/src/include -I../../radar/src/include -I../../rapformats/src/include -I../../rapmath/src/include -I../../rapplot/src/include -I../../shapelib/src/include -I../../tdrp/src/include -I../../titan/src/include -I../../toolsa/src/include -g -O2 -c cdata_util/regist_serv.c  -fno-common -DPIC -o cdata_util/.libs/regist_serv.o
libtool: compile:  clang++ -DHAVE_CONFIG_H -I. -I../../.. -DNO_JASPER_LIB -I./include -fPIC -I/usr/X11R6/include -I/opt/X11/include -I../../FiltAlg/src/include -I../../FiltAlgVirtVol/src/include -I../../Fmq/src/include -I../../Mdv/src/include -I../../Ncxx/src/include -I../../Radx/src/include -I../../Refract/src/include -I../../Spdb/src/include -I../../advect/src/include -I../../cidd/src/include -I../../contour/src/include -I../../dataport/src/include -I../../didss/src/include -I../../dsdata/src/include -I../../dsserver/src/include -I../../euclid/src/include -I../../grib/src/include -I../../grib2/src/include -I../../hydro/src/include -I../../kd/src/include -I../../physics/src/include -I../../radar/src/include -I../../rapformats/src/include -I../../rapmath/src/include -I../../rapplot/src/include -I../../shapelib/src/include -I../../tdrp/src/include -I../../titan/src/include -I../../toolsa/src/include -std=c++14 -c images/png_images.cc  -fno-common -DPIC -o images/.libs/png_images.o
libtool: compile:  clang -DHAVE_CONFIG_H -I. -I../../.. -DNO_JASPER_LIB -I./include -fPIC -I/usr/X11R6/include -I/opt/X11/include -I../../FiltAlg/src/include -I../../FiltAlgVirtVol/src/include -I../../Fmq/src/include -I../../Mdv/src/include -I../../Ncxx/src/include -I../../Radx/src/include -I../../Refract/src/include -I../../Spdb/src/include -I../../advect/src/include -I../../cidd/src/include -I../../contour/src/include -I../../dataport/src/include -I../../didss/src/include -I../../dsdata/src/include -I../../dsserver/src/include -I../../euclid/src/include -I../../grib/src/include -I../../grib2/src/include -I../../hydro/src/include -I../../kd/src/include -I../../physics/src/include -I../../radar/src/include -I../../rapformats/src/include -I../../rapmath/src/include -I../../rapplot/src/include -I../../shapelib/src/include -I../../tdrp/src/include -I../../titan/src/include -I../../toolsa/src/include -g -O2 -c cdata_util/latlon2xy.c -o cdata_util/latlon2xy.o >/dev/null 2>&1
libtool: compile:  clang -DHAVE_CONFIG_H -I. -I../../.. -DNO_JASPER_LIB -I./include -fPIC -I/usr/X11R6/include -I/opt/X11/include -I../../FiltAlg/src/include -I../../FiltAlgVirtVol/src/include -I../../Fmq/src/include -I../../Mdv/src/include -I../../Ncxx/src/include -I../../Radx/src/include -I../../Refract/src/include -I../../Spdb/src/include -I../../advect/src/include -I../../cidd/src/include -I../../contour/src/include -I../../dataport/src/include -I../../didss/src/include -I../../dsdata/src/include -I../../dsserver/src/include -I../../euclid/src/include -I../../grib/src/include -I../../grib2/src/include -I../../hydro/src/include -I../../kd/src/include -I../../physics/src/include -I../../radar/src/include -I../../rapformats/src/include -I../../rapmath/src/include -I../../rapplot/src/include -I../../shapelib/src/include -I../../tdrp/src/include -I../../titan/src/include -I../../toolsa/src/include -g -O2 -c cdata_util/regist_serv.c -o cdata_util/regist_serv.o >/dev/null 2>&1
In file included from images/png_images.cc:35:
./include/cidd/png_images.hh:38:10: fatal error: 'X11/Xlib.h' file not found
#include <X11/Xlib.h>
         ^~~~~~~~~~~~
1 error generated.
make[3]: *** [images/png_images.lo] Error 1
make[2]: *** [install-recursive] Error 1
make[1]: *** [install-recursive] Error 1
make: *** [install-recursive] Error 1

Do not report this issue to Homebrew/brew or Homebrew/core!

Traceback (most recent call last):
	22: from /usr/local/Homebrew/Library/Homebrew/build.rb:223:in `<main>'
	21: from /usr/local/Homebrew/Library/Homebrew/build.rb:134:in `install'
	20: from /usr/local/Homebrew/Library/Homebrew/utils.rb:531:in `with_env'
	19: from /usr/local/Homebrew/Library/Homebrew/build.rb:139:in `block in install'
	18: from /usr/local/Homebrew/Library/Homebrew/formula.rb:1215:in `brew'
	17: from /usr/local/Homebrew/Library/Homebrew/formula.rb:2236:in `stage'
	16: from /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/lib/ruby/2.6.0/forwardable.rb:230:in `stage'
	15: from /usr/local/Homebrew/Library/Homebrew/resource.rb:91:in `stage'
	14: from /usr/local/Homebrew/Library/Homebrew/resource.rb:116:in `unpack'
	13: from /usr/local/Homebrew/Library/Homebrew/resource.rb:197:in `mktemp'
	12: from /usr/local/Homebrew/Library/Homebrew/mktemp.rb:63:in `run'
	11: from /usr/local/Homebrew/Library/Homebrew/mktemp.rb:63:in `chdir'
	10: from /usr/local/Homebrew/Library/Homebrew/mktemp.rb:63:in `block in run'
	 9: from /usr/local/Homebrew/Library/Homebrew/resource.rb:121:in `block in unpack'
	 8: from /usr/local/Homebrew/Library/Homebrew/formula.rb:2256:in `block in stage'
	 7: from /usr/local/Homebrew/Library/Homebrew/utils.rb:531:in `with_env'
	 6: from /usr/local/Homebrew/Library/Homebrew/formula.rb:2257:in `block (2 levels) in stage'
	 5: from /usr/local/Homebrew/Library/Homebrew/formula.rb:1222:in `block in brew'
	 4: from /usr/local/Homebrew/Library/Homebrew/build.rb:171:in `block (2 levels) in install'
	 3: from /Users/marq789/Downloads/lrose-core.rb:33:in `install'
	 2: from /usr/local/Homebrew/Library/Homebrew/formula.rb:2043:in `system'
	 1: from /usr/local/Homebrew/Library/Homebrew/formula.rb:2043:in `open'
/usr/local/Homebrew/Library/Homebrew/formula.rb:2107:in `block in system': Failed executing: make install (BuildError)
	5: from /usr/local/Homebrew/Library/Homebrew/brew.rb:153:in `<main>'
	4: from /usr/local/Homebrew/Library/Homebrew/brew.rb:165:in `rescue in <main>'
	3: from /usr/local/Homebrew/Library/Homebrew/exceptions.rb:474:in `dump'
	2: from /usr/local/Homebrew/Library/Homebrew/exceptions.rb:420:in `issues'
	1: from /usr/local/Homebrew/Library/Homebrew/exceptions.rb:424:in `fetch_issues'
/usr/local/Homebrew/Library/Homebrew/utils/github.rb:323:in `issues_for_formula': undefined method `full_name' for nil:NilClass (NoMethodError)

**Comment by josephhardinee** [comment]
I've been working with Jim some I tracked it down to the script looking in /opt/X11/include rather than in /opt/X11/include/X11. This is something to do with homebrew recipe/environment. When using homebrew installer I ran into same issue as Jim, but when building from source directly (after using homebrew to get dependencies) it went through correctly.

**Comment by niconoe** [comment]
Same problem here, any solution in sight? I plan to also try the source install ASAP.

**Comment by mike-dixon** [comment]
The latest versions of OSX - monterey and ventura - do not appear to have this problem.
