### ISSUE TITLE
LROSE Install on Mac OS Catalina 10.15.7:  Installation Help!...Running out of ideas...Clang problem?

### ISSUE THREAD

**Issue by kakosiba** [NCAR/lrose-core#91]
Hi All,

I have been trying to install LROSE on MAC_OX Catalina to no avail...using 2 different methods...(and I am pretty sure I have all the dependencies installed)

Method 1.  Tried installing via "brew install lrose.rb"

A.  Similar to #90, I had an issue with ":x11 is depriciated!"...so I just replaced 'X11' with 'libx11' and it seemed to move past that issue (at least for now).  But, I now get the following (I didn't copy and past everything, but I highlighted what I *think* might be most relevant and I don't know how to fix): 

**Error: **Failed to load cask: lrose-core.rb
Cask 'lrose-core' is unreadable: wrong constant name #<Class:0x00007fd54f23b410>****
Warning: Treating lrose-core.rb as a formula.
==> Downloading https://github.com/NCAR/lrose-core/releases/download/lrose-core-20200701/lrose-core-20200719.src.mac_osx.tgz
Already downloaded: /Users/karenakosiba/Library/Caches/Homebrew/downloads/305606d0fc2ec4100e589eaf0aeac05067c7fc37e4b8fca063d998220fd42e76--lrose-core-20200719.src.mac_osx.tgz
==> ./configure --prefix=/usr/local/Cellar/lrose-core/core-20200719
==> make install
Last 15 lines from /Users/karenakosiba/Library/Logs/Homebrew/lrose-core/02.make:

_(Note:  skipped copy all the lines and lines of paths...could be something in there, but didn't look like it)_

**ld: library not found for -lnetcdf
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[4]: *** [tdrp_gen] Error 1**
make[3]: *** [install-recursive] Error 1
make[2]: *** [install-recursive] Error 1
make[1]: *** [install-recursive] Error 1
make: *** [install-recursive] Error 1

Do not report this issue to Homebrew/brew or Homebrew/core!

Traceback (most recent call last):
	22: from /usr/local/Homebrew/Library/Homebrew/build.rb:227:in `<main>'
	21: from /usr/local/Homebrew/Library/Homebrew/build.rb:134:in `install'
	20: from /usr/local/Homebrew/Library/Homebrew/utils.rb:532:in `with_env'
	19: from /usr/local/Homebrew/Library/Homebrew/build.rb:139:in `block in install'
	18: from /usr/local/Homebrew/Library/Homebrew/formula.rb:1216:in `brew'
	17: from /usr/local/Homebrew/Library/Homebrew/formula.rb:2237:in `stage'
	16: from /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/lib/ruby/2.6.0/forwardable.rb:230:in `stage'
	15: from /usr/local/Homebrew/Library/Homebrew/resource.rb:91:in `stage'
	14: from /usr/local/Homebrew/Library/Homebrew/resource.rb:116:in `unpack'
	13: from /usr/local/Homebrew/Library/Homebrew/resource.rb:197:in `mktemp'
	12: from /usr/local/Homebrew/Library/Homebrew/mktemp.rb:63:in `run'
	11: from /usr/local/Homebrew/Library/Homebrew/mktemp.rb:63:in `chdir'
	10: from /usr/local/Homebrew/Library/Homebrew/mktemp.rb:63:in `block in run'
	 9: from /usr/local/Homebrew/Library/Homebrew/resource.rb:121:in `block in unpack'
	 8: from /usr/local/Homebrew/Library/Homebrew/formula.rb:2257:in `block in stage'
	 7: from /usr/local/Homebrew/Library/Homebrew/utils.rb:532:in `with_env'
	 6: from /usr/local/Homebrew/Library/Homebrew/formula.rb:2258:in `block (2 levels) in stage'
	 5: from /usr/local/Homebrew/Library/Homebrew/formula.rb:1223:in `block in brew'
	 4: from /usr/local/Homebrew/Library/Homebrew/build.rb:175:in `block (2 levels) in install'
	 3: from /Users/karenakosiba/Downloads/lrose-core.rb:33:in `install'
	 2: from /usr/local/Homebrew/Library/Homebrew/formula.rb:2044:in `system'
	 1: from /usr/local/Homebrew/Library/Homebrew/formula.rb:2044:in `open'
/usr/local/Homebrew/Library/Homebrew/formula.rb:2108:in `block in system': Failed executing: make install (BuildError)
	5: from /usr/local/Homebrew/Library/Homebrew/brew.rb:155:in `<main>'
	4: from /usr/local/Homebrew/Library/Homebrew/brew.rb:167:in `rescue in <main>'
	3: from /usr/local/Homebrew/Library/Homebrew/exceptions.rb:475:in `dump'
	2: from /usr/local/Homebrew/Library/Homebrew/exceptions.rb:421:in `issues'
	1: from /usr/local/Homebrew/Library/Homebrew/exceptions.rb:425:in `fetch_issues'
/usr/local/Homebrew/Library/Homebrew/utils/github.rb:321:in `issues_for_formula': undefined method `full_name' for nil:NilClass (NoMethodError)

------------------
Method 2.  I tried to build from the source directly...at the "make install" step in ~/git/lrose-core/codebase/libs/tdrp/src, I get the following error...even though stdio.h exists:

		/bin/mkdir -p /Users/karenakosiba/lrose/include/tdrp; fi
if /bin/test -d include/tdrp; then \
	/bin/cp -rf include/tdrp /Users/karenakosiba/lrose/include; else \
	/bin/cp -rf include/*h /Users/karenakosiba/lrose/include; fi
if /bin/test -d /Users/karenakosiba/lrose/lib; then :; else \
		/bin/mkdir -p /Users/karenakosiba/lrose/lib; fi
/Applications/Xcode.app/Contents/Developer/usr/bin/make tdrp TARGET=all
if /bin/test -d tdrp; then cd tdrp; /Applications/Xcode.app/Contents/Developer/usr/bin/make all; fi ;
/Applications/Xcode.app/Contents/Developer/usr/bin/make _CC="gcc" _CPPC="g++" _FC="gfortran" _F90C="gfortran" \
	_F95C="gfortran" \
	DBUG_OPT_FLAGS="-O2" target 
echo Making library module ...
Making library module ...
/Applications/Xcode.app/Contents/Developer/usr/bin/make _CC="gcc" _CPPC="g++" _F90C="gfortran" DBUG_OPT_FLAGS="-O2" DEBUG_CFLAGS="" DEBUG_LIBS="" DEBUG_LDFLAGS="" SYS_LIBS="" SYS_CFLAGS=" -DOSX_LROSE -D_BSD_TYPES -DF_UNDERSCORE2 " lib
gcc   -DOSX_LROSE -D_BSD_TYPES -DF_UNDERSCORE2  -O2 -c -I../include -I/Users/karenakosiba/lrose/include   check.c
gcc: warning: couldn’t understand kern.osversion ‘19.6.0
In file included from check.c:35:0:
**../include/tdrp/tdrp.h:32:19: fatal error: stdio.h: No such file or directory
 #include <stdio.h>
                   ^
compilation terminated.**
make[4]: *** [check.o] Error 1
make[3]: *** [target] Error 2
make[2]: *** [opt] Error 2
make[1]: *** [tdrp] Error 2
make: *** [all] Error 2

------------------
Help :)!! Thanks!!

Best.
Karen

P.S. More than happy to tar up the Log files and send.

**Comment by ScottGunter** [comment]
Any resolution on this? Same MacOS and similar errors here, except I am using the 20210312 version. Thanks!

**Comment by gewitterblitz** [comment]
I have been unsuccessful in my attempts to install lrose with same OS configuration. Here are the steps I followed for installation:

> Downloaded lrose-core.rb from the [latest release](https://github.com/NCAR/lrose-core/releases/tag/lrose-core-20210524) and used homebrew (brew install lrose-core.rb). Here's the error message:

```
==> Downloading https://github.com/NCAR/lrose-core/releases/download/lrose-core-20210524/lrose-core-20210524.s
Already downloaded: /Users/ms/Library/Caches/Homebrew/downloads/596cd8f5869dd818fdd0524322d0b020c0dec5520f95175deed1e6cdd65dba5e--lrose-core-20210524.src.tgz
==> cmake ..
==> make -j 8 install
==> make -j 8 install
==> make -j 8 install
Last 15 lines from /Users/ms/Library/Logs/Homebrew/lrose-core/04.make:
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/cmath:327:9: error: no member named 'islessgreater' in the global namespace
using ::islessgreater;
      ~~^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/cmath:328:9: error: no member named 'isunordered' in the global namespace
using ::isunordered;
      ~~^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/cmath:329:9: error: no member named 'isunordered' in the global namespace
using ::isunordered;
      ~~^
[  1%] Building CXX object libs/Mdv/src/CMakeFiles/Mdv.dir/DsMdvx/msg_assemble.cc.o
13 errors generated.
make[2]: *** [libs/Mdv/src/CMakeFiles/Mdv.dir/ClimoStatCalc/StdDevStatCalc.cc.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [libs/Mdv/src/CMakeFiles/Mdv.dir/all] Error 2
make: *** [all] Error 2

Do not report this issue to Homebrew/brew or Homebrew/core!

Traceback (most recent call last):
	28: from /usr/local/Homebrew/Library/Homebrew/build.rb:229:in `<main>'
	27: from /usr/local/Homebrew/Library/Homebrew/build.rb:133:in `install'
	26: from /usr/local/Homebrew/Library/Homebrew/utils.rb:550:in `with_env'
	25: from /usr/local/Homebrew/Library/Homebrew/build.rb:138:in `block in install'
	24: from /usr/local/Homebrew/Library/Homebrew/formula.rb:1274:in `brew'
	23: from /usr/local/Homebrew/Library/Homebrew/formula.rb:2394:in `stage'
	22: from /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/lib/ruby/2.6.0/forwardable.rb:230:in `stage'
	21: from /usr/local/Homebrew/Library/Homebrew/resource.rb:91:in `stage'
	20: from /usr/local/Homebrew/Library/Homebrew/resource.rb:116:in `unpack'
	19: from /usr/local/Homebrew/Library/Homebrew/resource.rb:199:in `mktemp'
	18: from /usr/local/Homebrew/Library/Homebrew/mktemp.rb:63:in `run'
	17: from /usr/local/Homebrew/Library/Homebrew/mktemp.rb:63:in `chdir'
	16: from /usr/local/Homebrew/Library/Homebrew/mktemp.rb:63:in `block in run'
	15: from /usr/local/Homebrew/Library/Homebrew/resource.rb:117:in `block in unpack'
	14: from /usr/local/Homebrew/Library/Homebrew/download_strategy.rb:102:in `stage'
	13: from /usr/local/Homebrew/Library/Homebrew/download_strategy.rb:115:in `chdir'
	12: from /usr/local/Homebrew/Library/Homebrew/download_strategy.rb:115:in `chdir'
	11: from /usr/local/Homebrew/Library/Homebrew/resource.rb:121:in `block (2 levels) in unpack'
	10: from /usr/local/Homebrew/Library/Homebrew/formula.rb:2414:in `block in stage'
	 9: from /usr/local/Homebrew/Library/Homebrew/utils.rb:550:in `with_env'
	 8: from /usr/local/Homebrew/Library/Homebrew/formula.rb:2415:in `block (2 levels) in stage'
	 7: from /usr/local/Homebrew/Library/Homebrew/formula.rb:1281:in `block in brew'
	 6: from /usr/local/Homebrew/Library/Homebrew/build.rb:178:in `block (2 levels) in install'
	 5: from /Users/ms/Documents/LROSE_core_brew/lrose-core.rb:35:in `install'
	 4: from /Users/ms/Documents/LROSE_core_brew/lrose-core.rb:35:in `chdir'
	 3: from /Users/ms/Documents/LROSE_core_brew/lrose-core.rb:47:in `block in install'
	 2: from /usr/local/Homebrew/Library/Homebrew/formula.rb:2185:in `system'
	 1: from /usr/local/Homebrew/Library/Homebrew/formula.rb:2185:in `open'
/usr/local/Homebrew/Library/Homebrew/formula.rb:2249:in `block in system': Failed executing: make -j 8 install (BuildError)
	5: from /usr/local/Homebrew/Library/Homebrew/brew.rb:155:in `<main>'
	4: from /usr/local/Homebrew/Library/Homebrew/brew.rb:167:in `rescue in <main>'
	3: from /usr/local/Homebrew/Library/Homebrew/exceptions.rb:509:in `dump'
	2: from /usr/local/Homebrew/Library/Homebrew/exceptions.rb:455:in `issues'
	1: from /usr/local/Homebrew/Library/Homebrew/exceptions.rb:459:in `fetch_issues'
/usr/local/Homebrew/Library/Homebrew/utils/github.rb:60:in `issues_for_formula': undefined method `full_name' for nil:NilClass (NoMethodError)
```


**Also tried the [previous release](https://github.com/NCAR/lrose-core/releases/tag/lrose-core-20210216) but similar error message:**

```
Already downloaded: /Users/ms/Library/Caches/Homebrew/downloads/5b7c43b5e5ac740d407ac3e0ddcbd4c093fccf9e66a6248d5d325c0ead15a217--lrose-core-20210312.src.tgz
/Users/ms/Documents/LROSE_core_brew/lrose-core.rb:33: warning: conflicting chdir during another chdir block
/Users/ms/Documents/LROSE_core_brew/lrose-core.rb:35: warning: conflicting chdir during another chdir block
==> cmake ..
==> make -j 8 install
Last 15 lines from /Users/ms/Library/Logs/Homebrew/lrose-core/02.make:
In file included from /tmp/lrose-core-20210726-83728-1he0vpi/lrose-core-20210312.src/codebase/libs/Mdv/src/ClimoStatCalc/StdDevStatCalc.cc:39:
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/cmath:327:9: error: no member named 'islessgreater' in the global namespace
using ::islessgreater;
      ~~^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/cmath:328:9: error: no member named 'isunordered' in the global namespace
using ::isunordered;
      ~~^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/cmath:329:9: error: no member named 'isunordered' in the global namespace
using ::isunordered;
      ~~^
13 errors generated.
make[2]: *** [libs/Mdv/src/CMakeFiles/Mdv.dir/ClimoStatCalc/StdDevStatCalc.cc.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [libs/Mdv/src/CMakeFiles/Mdv.dir/all] Error 2
make: *** [all] Error 2

Do not report this issue to Homebrew/brew or Homebrew/core!

Traceback (most recent call last):
	26: from /usr/local/Homebrew/Library/Homebrew/build.rb:229:in `<main>'
	25: from /usr/local/Homebrew/Library/Homebrew/build.rb:133:in `install'
	24: from /usr/local/Homebrew/Library/Homebrew/utils.rb:550:in `with_env'
	23: from /usr/local/Homebrew/Library/Homebrew/build.rb:138:in `block in install'
	22: from /usr/local/Homebrew/Library/Homebrew/formula.rb:1274:in `brew'
	21: from /usr/local/Homebrew/Library/Homebrew/formula.rb:2394:in `stage'
	20: from /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/lib/ruby/2.6.0/forwardable.rb:230:in `stage'
	19: from /usr/local/Homebrew/Library/Homebrew/resource.rb:91:in `stage'
	18: from /usr/local/Homebrew/Library/Homebrew/resource.rb:116:in `unpack'
	17: from /usr/local/Homebrew/Library/Homebrew/resource.rb:199:in `mktemp'
	16: from /usr/local/Homebrew/Library/Homebrew/mktemp.rb:63:in `run'
	15: from /usr/local/Homebrew/Library/Homebrew/mktemp.rb:63:in `chdir'
	14: from /usr/local/Homebrew/Library/Homebrew/mktemp.rb:63:in `block in run'
	13: from /usr/local/Homebrew/Library/Homebrew/resource.rb:117:in `block in unpack'
	12: from /usr/local/Homebrew/Library/Homebrew/download_strategy.rb:102:in `stage'
	11: from /usr/local/Homebrew/Library/Homebrew/download_strategy.rb:115:in `chdir'
	10: from /usr/local/Homebrew/Library/Homebrew/download_strategy.rb:115:in `chdir'
	 9: from /usr/local/Homebrew/Library/Homebrew/resource.rb:121:in `block (2 levels) in unpack'
	 8: from /usr/local/Homebrew/Library/Homebrew/formula.rb:2414:in `block in stage'
	 7: from /usr/local/Homebrew/Library/Homebrew/utils.rb:550:in `with_env'
	 6: from /usr/local/Homebrew/Library/Homebrew/formula.rb:2415:in `block (2 levels) in stage'
	 5: from /usr/local/Homebrew/Library/Homebrew/formula.rb:1281:in `block in brew'
	 4: from /usr/local/Homebrew/Library/Homebrew/build.rb:178:in `block (2 levels) in install'
	 3: from /Users/ms/Documents/LROSE_core_brew/lrose-core.rb:37:in `install'
	 2: from /usr/local/Homebrew/Library/Homebrew/formula.rb:2185:in `system'
	 1: from /usr/local/Homebrew/Library/Homebrew/formula.rb:2185:in `open'
/usr/local/Homebrew/Library/Homebrew/formula.rb:2249:in `block in system': Failed executing: make -j 8 install (BuildError)
	5: from /usr/local/Homebrew/Library/Homebrew/brew.rb:155:in `<main>'
	4: from /usr/local/Homebrew/Library/Homebrew/brew.rb:167:in `rescue in <main>'
	3: from /usr/local/Homebrew/Library/Homebrew/exceptions.rb:509:in `dump'
	2: from /usr/local/Homebrew/Library/Homebrew/exceptions.rb:455:in `issues'
	1: from /usr/local/Homebrew/Library/Homebrew/exceptions.rb:459:in `fetch_issues'
/usr/local/Homebrew/Library/Homebrew/utils/github.rb:60:in `issues_for_formula': undefined method `full_name' for nil:NilClass (NoMethodError)
```
Googling the error message led me to this[ thread](https://forums.swift.org/t/is-anyone-else-getting-this-error-when-building-the-compiler-from-master-on-macos/36113) which suggests deleting the xcode command line tools but once I do that and try `brew install lrose-core.rb`, I get this error:

```
Error: Failed to load cask: lrose-core.rb
Cask 'lrose-core' is unreadable: wrong constant name #<Class:0x00007f91b54b99b8>
Warning: Treating lrose-core.rb as a formula.
==> Downloading https://github.com/NCAR/lrose-core/releases/download/lrose-core-20210524/lrose-core-20210524.s
Already downloaded: /Users/ms/Library/Caches/Homebrew/downloads/596cd8f5869dd818fdd0524322d0b020c0dec5520f95175deed1e6cdd65dba5e--lrose-core-20210524.src.tgz
Error: Xcode alone is not sufficient on Catalina.
Install the Command Line Tools:
  xcode-select --install
```

Has anyone else encountered this problem? If yes, then how did you resolve it?

**Comment by gewitterblitz** [comment]
In case anyone is still stuck and interested in the solution, I have posted a workaround here:
http://forum.lrose.net/t/installing-lrose-on-macos-catalina/56

**Comment by mike-dixon** [comment]
Catalina is no longer supported by lrose.
